name: Test on Linux

on:
  pull_request:
    branches:
    - develop
  push:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node:
          - 8
          - 10

    name: Test on Node ${{ matrix.node }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup runtime
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: |
          npm install -g yarn
          yarn

      - name: Test
        run: |
          yarn test
